### ISSUE TITLE
Ripgrep not working

### ISSUE THREAD

**Issue by diocletiann** [kapitanluffy/sublime-context-keeper#10]
I can't seem to get ripgrep to work, the overlay shows only opened files. I have a folder loaded and this is my config:
```
{
    "ripgrep_path": "/opt/homebrew/bin/rg",
    "enable_tags": true,
    // "debug": false,
    "jump_to_most_recent_on_show": false,
    "preview_on_highlight": false,
    "enable_context_preview": false,
}
```

**Comment by kapitanluffy** [comment]
add this `only_show_unopened_files_on_empty_window: False`

**Comment by diocletiann** [comment]
> add this `only_show_unopened_files_on_empty_window: False`

Now they are showing up in the results but they don't open.

**Comment by kapitanluffy** [comment]
Try restarting Sublime and see if that resolves the issue

**Comment by kapitanluffy** [comment]
I assume you are using a Linux variant? Latest version should fix this now. Sorry, it took a while.
