### ISSUE TITLE
set default "max_open_tabs": 100, to 0

### ISSUE THREAD

**Issue by 9840380** [kapitanluffy/sublime-context-keeper#12]
For several days I could not understand what was closing the tabs. It doesn't appear in the console at all.
I thought it was a glitch and first removed the plugin. 
Not always a person rereads all the options on setting, and it can be a big surprise when tabs are closed automaticly.

**Comment by kapitanluffy** [comment]
This might be way too late of a reply but I appreciate you opening up an issue. In the latest release, I increased the value of `max_open_tabs` to 1000. Still, you can disable it by setting it to 0.
