### ISSUE TITLE
Compass Navigator does not switch to another tab when called right after Goto Anything

### ISSUE THREAD

**Issue by d0vgan** [kapitanluffy/sublime-context-keeper#13]
Steps to reproduce:
1. Press Ctrl+P to show the Goto Anything overlay
2. Press Down or Up a few times to change the current file by means of Goto Anything
3. Press Esc to close the Goto Anything (this also switches to the file that was active before calling Goto Anything)
4. Press Ctrl,Ctrl (or whatever key binding is specified for "compass_show") to show the Compass Navigator
5. Ensure the file selected in the Compass Navigator is not the currently active file
6. Press Enter to close the Compass Navigator and activate the selected file

The Expected behavior: the selected file should become active.
The Actual behavior: the previously active file remains active, as if the Compass Navigator did not do anything.

**Comment by kapitanluffy** [comment]
Seems like this is similar to an issue I have been hunting for a while. Does it happen consistently? Do you mind making a short clip reproducing it? I was trying it and it does not seem to trigger the bug. Thank you!

**Comment by d0vgan** [comment]
It's always reproducible for me.
I've recorded a .gif-animated screenshot.
(It did not capture the `Ctrl,Ctrl` which has the following key binding: 
```
{
	"keys": ["ctrl", "ctrl"],
	"command": "compass_close",
	"context": [
		{"key": "compass"},
		{"key": "overlay_visible", "operand": true, "operator": "equal"},
		{"key": "panel_has_focus", "operand": false, "operator": "equal"}
	]
},
{
	"keys": ["ctrl", "ctrl"],
	"command": "compass_show", "args": {"forward": true},
	"context": [
		{"key": "compass"},
		{"key": "overlay_visible", "operand": false, "operator": "equal"}
	]
},
```
)

![Sublime_GoTo_Compass](https://github.com/user-attachments/assets/b8fe5a3d-dc4a-4fed-a590-f09100f3b851)

**Comment by d0vgan** [comment]
And here are my corresponding bindings for `Enter` and `Escape`, just in case:
```
{
	"keys": ["enter"],
	"command": "compass_close",
	"context": [
		{"key": "compass"},
		{"key": "overlay_visible", "operand": true, "operator": "equal"},
		{"key": "panel_has_focus", "operand": false, "operator": "equal"}
	]
},
{
	"keys": ["escape"],
	"command": "compass_close", "args": {"reset": true},
	"context": [
		{"key": "compass"},
		{"key": "overlay_visible", "operand": true, "operator": "equal"},
		{"key": "panel_has_focus", "operand": false, "operator": "equal"}
	]
}
```

**Comment by d0vgan** [comment]
I've modified the file "show.py" a little bit to understand what is happening within the method `on_done`:
```
    def on_done(self, index, items, items_meta: List[Union[SheetGroup, File]]):
        state = plugin_state()

        print('on_done: index =', index)
        if index == -1:
            index = state["highlighted_index"]

        print('on_done: state["is_reset"] =', state["is_reset"])
        if state["is_reset"] is True:
            index = 0
            state["is_reset"] = False
   
        ...         
```

And here is what is logged in Sublime's console in the situation described above:
```
on_done: index = 2
on_done: state["is_reset"] = True
```

So... Looks like the value of `state["is_reset"]` is set to `True` somewhere in the code, and it leads to reseting the `index` to `0`.

**Comment by d0vgan** [comment]
OK, looks like I was able to track that down: by adding the following to the "close.py":
```
class CompassCloseCommand(sublime_plugin.WindowCommand):
    def run(self, **kwargs):
        state = plugin_state()
        state["is_reset"] = kwargs.get("reset", False)
        print('CompassCloseCommand.run: state["is_reset"] =', state["is_reset"])

        self.window.run_command("hide_overlay")
```

I can clearly see in Sublime's console:
```
CompassCloseCommand.run: state["is_reset"] = True
```
when I press Escape _in the Goto Anything overlay_!
I.e. when Escape is pressed in the Goto Anything, it is somehow processed by the `CompassCloseCommand`!


Probably this key binding:
```
	{
		"keys": ["escape"],
		"command": "compass_close", "args": {"reset": true},
		"context": [
			{"key": "compass"},
			{"key": "overlay_visible", "operand": true, "operator": "equal"},
			{"key": "panel_has_focus", "operand": false, "operator": "equal"}
		]
	}
```
somehow did not take `{"key": "compass"}` into account?
( Frankly, I don't understand how `{"key": "compass"}` is expected to work... It is not something I could find here: https://www.sublimetext.com/docs/key_bindings.html )

**Comment by d0vgan** [comment]
I don't really understand how the entire plugins' infrastructure works, but maybe you could add something like
```
class CompassShowCommand(sublime_plugin.WindowCommand):
    def run(self, **kwargs):
        ...
        state["is_compass"] = True
        self.window.show_quick_panel(...)
        state["is_compass"] = False
```
and check for the value of the `state["is_compass"]` in each and every handler of Compass'es commands?

**Comment by kapitanluffy** [comment]
@d0vgan thank you so much for looking into it. I will take a look some time later. 

I have one question though. Are your keybindings the default ones or you have customized them a bit? Can you try if it also happens using the default keybindings.

**Comment by d0vgan** [comment]
I can't reproduce it with the default key bindings. However, I believe that the quick panel should be closed by Escape _without changing the active file_, hence I do need the custom key bindings I mentioned above.
Anyway, I've created a work-in-progress pull request just to demonstrate the approach that fixes the problem. The idea is simple: we handle certain commands only when Compass is visible:
https://github.com/kapitanluffy/sublime-compass/pull/15
This is a draft and raw implementation, but it already fixes the problem with Escape key pressed in the Go To Anything but handled by Compass.

**Comment by kapitanluffy** [comment]
Hi, thank you so much for putting such effort looking into this. I replicated your setup and I realized that you were binding enter and escape. 

It is highly suggested that you don't bind something in the enter and escape keys because ST listens for events on those. That is why I have odd default bindings for the ones you have overridden (e.g. `[alt, alt]` for `[escape]`)

You can fix this problem by removing your bindings to the Enter and Escape keys. Pressing Enter is not activating the file because instead of "selecting" an item, it closes the compass.

Pressing "escape" should close the compass by default without binding it to compass_close command.

Although, going through your comments, I assume you want to replicate the Goto Anything's feature where pressing Escape returns you to the previous file. I guess that is a bug that I have overlooked. I will look into that.

**Comment by kapitanluffy** [comment]
> Although, going through your comments, I assume you want to replicate the Goto Anything's feature where pressing Escape returns you to the previous file. I guess that is a bug that I have overlooked. I will look into that.

I fixed this now in the latest release

**Comment by d0vgan** [comment]
Thank you!
Regarding the `Enter` key, I actually have 2 key bindings to avoid the conflicts between GoTo and Compass Navigator:
```
// CompassNavigator: close and activate the selected file
{
	"keys": ["enter"],
	"command": "compass_close",
	"args": {"reset": false},
	"context": [
		{"key": "compass"},
		{"key": "overlay_visible", "operand": true, "operator": "equal"},
		{"key": "panel_has_focus", "operand": false, "operator": "equal"}
	]
},

// avoiding conflicts with Compass Navigator
{
	"keys": ["enter"],
	"command": "select",
	"context": [
		{ "key": "overlay_has_focus", "operator": "equal", "operand": true },
		{ "key": "overlay_name", "operator": "equal", "operand": "goto" }
	]
},
```
