### ISSUE TITLE
Redundant entries

### ISSUE THREAD

**Issue by reagle** [kapitanluffy/sublime-context-keeper#3]
Hi, thanks for this. If I have two tabs open, why does it show 4 entries?

<img width="824" alt="SCR-20231007-ozzs" src="https://github.com/kapitanluffy/sublime-compass/assets/596814/e88a1f52-21fa-4c07-8530-a5186fe8ccc8">

**Comment by kapitanluffy** [comment]
Fixed this on the next release. Those duplicate items are supposedly for the `#tabs` filter when you enable the `enable_tags` setting.

I'll close this issue for now. Feel free to reopen if you are still having the same issue

**Comment by reagle** [comment]
Hi, I don't know what the tags feature is. (Don't see documentation on the README.) 

I'm running 2.1.2 and `"enable_tags": false,` but I'M still seeing 4 entries as in the screenshot above.

Also, what order are the tabs placed in. Last used, or left-to-right, or something else? I have `"jump_to_most_recent_on_show": true,` to default, so that sets last used? If it's false, then what is the order?

**Comment by kapitanluffy** [comment]
I assume you restarted Sublime? Can you try it on a new project and see if that still happens. It might be a cache problem.

As for the order, it shows MRU (last used). If `jump_to_most_recent_on_show` is enabled, it will show the compass and "jump" to the tab below your current tab. Disabling it will show the compass without moving it.

**Comment by reagle** [comment]
Perhaps I failed to restart. I just did so now and I'm not see duplicate entries. Also, perhaps, the tags and jump features could be documented in the README? Thanks for your help.
