### ISSUE TITLE
Not showing stack

### ISSUE THREAD

**Issue by abhishek72850** [kapitanluffy/sublime-context-keeper#4]
> By default, ctrl+tab jumps you to the next view in the MRU stack without showing the stack. Compass provides you a visual guide of where you have been.

I enabled the key binding, but it still it jumps without showing any stack UI

**Comment by kapitanluffy** [comment]
Have you restarted your sublime? Also, do you have folders?

**Comment by abhishek72850** [comment]
I did restarted and i have folders in my project, also debug is on but i
dont see any logs in console related to plugin

**Comment by kapitanluffy** [comment]
Can you check the console and put here any errors happening when:

- opening sublime
- pressing ctrl+tab

**Comment by reagle** [comment]
I have to enable the key binding for `ctrl+tab` to prompt Compass. However, when I do so, if I hit `ctrl+tab` repeatedly, I still cycle through my tabs _without_ the compass indicator changing. BTW: I think the README prose should be tweaked to: "By default, ctrl+tab in Sublime Text jumps you to the next view in the MRU (Most Recently Used) stack without showing the stack. Compass provides you a visual guide of where you have been."

**Comment by kapitanluffy** [comment]
> I have to enable the key binding for `ctrl+tab` to prompt Compass. However, when I do so, if I hit `ctrl+tab` repeatedly, I still cycle through my tabs _without_ the compass indicator changing. BTW: I think the README prose should be tweaked to: "By default, ctrl+tab in Sublime Text jumps you to the next view in the MRU (Most Recently Used) stack without showing the stack. Compass provides you a visual guide of where you have been."

The highlight does not change? What are your settings?

**Comment by reagle** [comment]
I don't have any settings presently since I don't understand them. It's the default empty `{ }`.

**Comment by reagle** [comment]
I think it works sometimes, but in this animated GIF you can see I'm hit `ctrl+tab`, prompting Compass to open, but as I continue to hit it the active tab changes but the Compass highlight/indicator doesn't.

![compass-indicator](https://github.com/kapitanluffy/sublime-compass/assets/596814/4e7667fe-4fd6-4863-94aa-9795dedef7e1)

**Comment by kapitanluffy** [comment]
> I think it works sometimes, but in this animated GIF you can see I'm hit `ctrl+tab`, prompting Compass to open, but as I continue to hit it the active tab changes but the Compass highlight/indicator doesn't.
> 
> ![compass-indicator](https://github.com/kapitanluffy/sublime-compass/assets/596814/4e7667fe-4fd6-4863-94aa-9795dedef7e1)
> 

whoa. ok, that's bad. I'll look into that. I'd appreciate it if you create a separate issue.

**Comment by reagle** [comment]
Okay: https://github.com/kapitanluffy/sublime-compass/issues/6

**Comment by abhishek72850** [comment]
Check screen recording for `ctrl + tab`
check screenshot for settings and key bindings

https://github.com/kapitanluffy/sublime-compass/assets/18554923/a68d6b96-270a-4727-9cc7-47358a39d88c

**Comment by kapitanluffy** [comment]
> Check screen recording for `ctrl + tab` check screenshot for settings and key bindings
> Screen.Recording.2023-10-10.at.7.06.25.PM.mov

Can you show the keybindings?

You can also try `sublime.log_commands(True)` to show if the command is even triggering. If it is not, you can try binding it to other keys.

**Comment by abhishek72850** [comment]
oh damn forgot to attach screenshots
<img width="1399" alt="Screenshot 2023-10-10 at 7 05 53 PM" src="https://github.com/kapitanluffy/sublime-compass/assets/18554923/e330e394-d687-4a7c-82b6-5ea00709a874">
<img width="1428" alt="Screenshot 2023-10-10 at 7 05 59 PM" src="https://github.com/kapitanluffy/sublime-compass/assets/18554923/e321a798-a2db-4616-b7e5-46536c88f0fe">

**Comment by kapitanluffy** [comment]
so yeah. you only enabled the compass move command. i suggest you enable the keybinds with ctrl+tab and ctrl+shift+tab.

**Comment by abhishekk72850** [comment]
Its enabled, check the screenshot

**Comment by kapitanluffy** [comment]
@abhishek72850 for better context, you will see this on the default keybindings

```
    // // override next/prev view stack keybinds
    // {
    //     "keys": ["ctrl+tab"],
    //     "command": "compass_show",
    //     "args": {
    //         "forward": true
    //     },
    //     "context": [
    //         { "key": "overlay_visible", "operator": "equal", "operand": false },
    //         { "key": "compass" },
    //     ]
    // },
    // {
    //     "keys": ["ctrl+shift+tab"],
    //     "command": "compass_show",
    //     "args": {
    //         "forward": false
    //     },
    //     "context": [
    //         { "key": "overlay_visible", "operator": "equal", "operand": false },
    //         { "key": "compass" },
    //     ]
    // },
```
notice the command, this is `compass_show`

**Comment by abhishek72850** [comment]
Ohh, both have same key bindings that's why i missed it, its working now thanks for your effort.
