### ISSUE TITLE
Indicator/highlight not changing with changing tab

### ISSUE THREAD

**Issue by reagle** [kapitanluffy/sublime-context-keeper#6]
I have enabled the key binding for ctrl+tab to prompt Compass. However, when I do so, if I hit ctrl+tab repeatedly, I still cycle through my tabs without the compass indicator changing. 

![](https://user-images.githubusercontent.com/596814/273910012-4e7667fe-4fd6-4863-94aa-9795dedef7e1.gif)

**Comment by kapitanluffy** [comment]
Can you try `sublime.log_commands(True)` in the console? I have a hunch that a keybinding on ctrl+tab is not triggering the move command. Maybe it is conflicting with your other keybinds.

**Comment by reagle** [comment]
```
>>> sublime.log_commands(True)
command: compass_show {"forward": true}
command: gs_draw_status_bar
command: next_view_in_stack
command: next_view_in_stack
command: next_view_in_stack
command: prev_view_in_stack
command: prev_view_in_stack
```

```
[
	{
        "keys": ["ctrl+tab"],
        "command": "compass_show",
        "args": {
            "forward": true
        },
        "context": [
            { "key": "overlay_visible", "operator": "equal", "operand": false },
            { "key": "compass" },
        ]
    },
	{
	        "keys": ["ctrl+shift+tab"],
	        "command": "compass_show",
	        "args": {
	            "forward": false
	        },
	        "context": [
	            { "key": "overlay_visible", "operator": "equal", "operand": false },
	            { "key": "compass" },
	        ]
	    },

]
```

**Comment by kapitanluffy** [comment]
Enable these

![Screenshot_20231011_005635_GitHub.jpg](https://github.com/kapitanluffy/sublime-compass/assets/485799/77e2ec94-f0a6-4810-91a7-8e00472ac084)

**Comment by reagle** [comment]
Okay, I think that's working, but now I'm having a different issue, which I'll open a new issue for.
