### ISSUE TITLE
Let's add a hint to the plugin's name to explicitly explain its purpose

### ISSUE THREAD

**Issue by d0vgan** [kapitanluffy/sublime-context-keeper#9]
For a long time I was searching for ability to have a Ctrl+Tab List of the opened files (tabs) in MRU order similarly to the one in VS Code or Notepad++. And Sublime Text core developers for some reason do not want to add that to the editor.
So I was searching for existing plugins that could propose such an ability. I was searching for plugins containing anything like "File List", "Tab List", "Opened Files", "Opened Tabs", "MRU", "Ctrl Tab" in their name or description.
The closest one was Tab Filter, which is great except for its files (tabs) list is not in the MRU order.
Just recently, absolutely accidentally, I noticed that somebody mentioned Compass Navigator as a plugin that shows the files (tabs) list in the MRU order. So I tried Compass Navigator - and it is the closest implementation of the Ctrl+Tab List for Sublime Text I've ever seen.
So I'm wondering: could you add keywords similar to Opened tabs/files, MRU, Ctrl+Tab to the plugin description to allow to find it by these keywords among all the other plugins?
Here is a link to the corresponding topic in the Sublime Forum:
https://forum.sublimetext.com/t/shortcut-for-the-tabs-menu/63533

**Comment by kapitanluffy** [comment]
Sure. I updated the description. Afaik, PC filters packages using the description too. Thanks for bringing this up!
